"""
350 skincare ingredients for database seeding.

This list acts as the initial 'Brain' for the Skin Lens app. 
It maps raw chemical names to:
1. Safety Ratings (Safe, Moderate, Irritant, Avoid)
2. Clinical Descriptions (What it actually does)
3. Skin Type Compatibility (Who should use it)
"""

# ------------------------------------------------------------------
# KEY LEGEND:
# "name": The string found on the bottle label (e.g., "Glycerin")
# "safety_rating": The clinical verdict (Mapped to the SafetyRating Enum)
# "description": A short, user-friendly explanation of the chemical.
# "compatible_skin_types": A string filter for the Quiz/Recommendation engine.
# ------------------------------------------------------------------

INGREDIENTS = [
    # Humectants
    {"name": "Glycerin", "safety_rating": "Safe", "description": "Powerful humectant that draws moisture into the skin. Suitable for all skin types.", "compatible_skin_types": "All"},
    {"name": "Hyaluronic Acid", "safety_rating": "Safe", "description": "Powerful humectant that holds up to 1000x its weight in water. Keeps skin plump and hydrated.", "compatible_skin_types": "All"},
    {"name": "Propylene Glycol", "safety_rating": "Safe", "description": "Humectant and solvent. Helps other ingredients penetrate skin. Generally well-tolerated.", "compatible_skin_types": "All"},
    {"name": "Sodium Hyaluronate", "safety_rating": "Safe", "description": "Sodium salt of hyaluronic acid. Smaller molecule for deeper penetration.", "compatible_skin_types": "All"},
    {"name": "Hyaluronate", "safety_rating": "Safe", "description": "Sodium hyaluronate variant. Humectant with excellent moisture retention.", "compatible_skin_types": "All"},
    {"name": "Butylene Glycol", "safety_rating": "Safe", "description": "Humectant and solvent. Helps improve product texture and spreadability.", "compatible_skin_types": "All"},
    {"name": "Pentylene Glycol", "safety_rating": "Safe", "description": "Humectant with mild preservative properties. Gentle on skin.", "compatible_skin_types": "All"},
    {"name": "Propanediol", "safety_rating": "Safe", "description": "Plant-derived humectant. Alternative to propylene glycol.", "compatible_skin_types": "All"},
    {"name": "Sorbitol", "safety_rating": "Safe", "description": "Sugar alcohol humectant. Adds moisture without stickiness.", "compatible_skin_types": "All"},
    {"name": "Xylitol", "safety_rating": "Safe", "description": "Natural humectant with antimicrobial properties.", "compatible_skin_types": "All"},
    {"name": "Erythritol", "safety_rating": "Safe", "description": "Sugar alcohol humectant. Lightweight and non-sticky.", "compatible_skin_types": "All"},
    {"name": "Urea", "safety_rating": "Safe", "description": "Natural moisturizing factor. Helps exfoliate and hydrate dry skin.", "compatible_skin_types": "Dry,All"},
    {"name": "Honey", "safety_rating": "Safe", "description": "Natural humectant with antibacterial and soothing properties.", "compatible_skin_types": "All"},
    {"name": "Aloe Vera", "safety_rating": "Safe", "description": "Soothing humectant with anti-inflammatory properties. Calms irritated skin.", "compatible_skin_types": "All"},
    {"name": "Aloe Barbadensis Leaf Juice", "safety_rating": "Safe", "description": "INCI name for aloe vera. Hydrating and soothing.", "compatible_skin_types": "All"},
    {"name": "Sodium PCA", "safety_rating": "Safe", "description": "Natural moisturizing factor. Helps maintain skin hydration.", "compatible_skin_types": "All"},
    {"name": "Lactic Acid", "safety_rating": "Moderate", "description": "Alpha hydroxy acid. Exfoliates and hydrates. Use with sunscreen.", "compatible_skin_types": "Dry,All"},
    {"name": "Lactitol", "safety_rating": "Safe", "description": "Sugar alcohol humectant. Gentle moisture retention.", "compatible_skin_types": "All"},
    {"name": "Trehalose", "safety_rating": "Safe", "description": "Sugar that protects cells from dehydration. Stabilizes skin barrier.", "compatible_skin_types": "All"},
    {"name": "Betaine", "safety_rating": "Safe", "description": "Amino acid derivative. Humectant. Helps skin retain moisture.", "compatible_skin_types": "All"},
    # Preservatives
    {"name": "Methylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. Linked to endocrine disruption and skin irritation.", "compatible_skin_types": "All"},
    {"name": "Propylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. Potential endocrine disruptor.", "compatible_skin_types": "All"},
    {"name": "Ethylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. May cause allergic reactions.", "compatible_skin_types": "All"},
    {"name": "Butylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. Restricted in EU.", "compatible_skin_types": "All"},
    {"name": "Isobutylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. Potential hormone disruptor.", "compatible_skin_types": "All"},
    {"name": "Phenoxyethanol", "safety_rating": "Moderate", "description": "Preservative. Can cause irritation in sensitive skin. Generally safe at low concentrations.", "compatible_skin_types": "All"},
    {"name": "Sodium Benzoate", "safety_rating": "Safe", "description": "Mild preservative. Often used with potassium sorbate.", "compatible_skin_types": "All"},
    {"name": "Potassium Sorbate", "safety_rating": "Safe", "description": "Mild preservative. Effective against mold and yeast.", "compatible_skin_types": "All"},
    {"name": "Benzyl Alcohol", "safety_rating": "Moderate", "description": "Preservative and solvent. Can cause irritation in some.", "compatible_skin_types": "All"},
    {"name": "Dehydroacetic Acid", "safety_rating": "Safe", "description": "Preservative. Effective at low concentrations.", "compatible_skin_types": "All"},
    {"name": "Sodium Dehydroacetate", "safety_rating": "Safe", "description": "Salt form of dehydroacetic acid. Preservative.", "compatible_skin_types": "All"},
    {"name": "Caprylyl Glycol", "safety_rating": "Safe", "description": "Humectant and preservative booster. Often used in paraben-free formulas.", "compatible_skin_types": "All"},
    {"name": "Ethylhexylglycerin", "safety_rating": "Safe", "description": "Preservative booster. Enhances efficacy of other preservatives.", "compatible_skin_types": "All"},
    {"name": "Formaldehyde", "safety_rating": "Avoid", "description": "Carcinogenic preservative. Banned in many countries.", "compatible_skin_types": "All"},
    {"name": "Quaternium-15", "safety_rating": "Avoid", "description": "Formaldehyde-releasing preservative. Can cause skin irritation.", "compatible_skin_types": "All"},
    {"name": "DMDM Hydantoin", "safety_rating": "Avoid", "description": "Formaldehyde-releasing preservative. Can cause allergic reactions.", "compatible_skin_types": "All"},
    {"name": "Imidazolidinyl Urea", "safety_rating": "Avoid", "description": "Formaldehyde-releasing preservative. Potential allergen.", "compatible_skin_types": "All"},
    {"name": "Diazolidinyl Urea", "safety_rating": "Avoid", "description": "Formaldehyde-releasing preservative. May cause contact dermatitis.", "compatible_skin_types": "All"},
    {"name": "Methylisothiazolinone", "safety_rating": "Irritant", "description": "Preservative. Can cause severe allergic reactions. Restricted in EU.", "compatible_skin_types": "All"},
    {"name": "Methylchloroisothiazolinone", "safety_rating": "Irritant", "description": "Preservative. Strong allergen. Often paired with methylisothiazolinone.", "compatible_skin_types": "All"},
    # Surfactants
    {"name": "Sodium Lauryl Sulfate", "safety_rating": "Irritant", "description": "Harsh foaming agent. Can strip skin of natural oils and cause dryness.", "compatible_skin_types": "Oily"},
    {"name": "Sodium Laureth Sulfate", "safety_rating": "Moderate", "description": "Gentler foaming agent than SLS. Can still cause dryness in some.", "compatible_skin_types": "Oily,All"},
    {"name": "Cocamidopropyl Betaine", "safety_rating": "Safe", "description": "Gentle foaming surfactant. Derived from coconut.", "compatible_skin_types": "All"},
    {"name": "Sodium Cocoyl Isethionate", "safety_rating": "Safe", "description": "Mild surfactant. Gentle cleanser suitable for sensitive skin.", "compatible_skin_types": "All"},
    {"name": "Disodium Laureth Sulfosuccinate", "safety_rating": "Safe", "description": "Mild surfactant. Gentle cleansing without stripping.", "compatible_skin_types": "All"},
    {"name": "Sodium Lauroyl Sarcosinate", "safety_rating": "Safe", "description": "Mild surfactant. Derived from amino acids. Gentle.", "compatible_skin_types": "All"},
    {"name": "Decyl Glucoside", "safety_rating": "Safe", "description": "Plant-derived surfactant. Gentle and biodegradable.", "compatible_skin_types": "All"},
    {"name": "Lauryl Glucoside", "safety_rating": "Safe", "description": "Plant-derived surfactant. Mild cleansing.", "compatible_skin_types": "All"},
    {"name": "Coco-Glucoside", "safety_rating": "Safe", "description": "Plant-derived surfactant. Gentle and eco-friendly.", "compatible_skin_types": "All"},
    {"name": "Sodium Coco-Sulfate", "safety_rating": "Moderate", "description": "Gentler alternative to SLS. Still a sulfate.", "compatible_skin_types": "Oily,All"},
    {"name": "Cocamide DEA", "safety_rating": "Moderate", "description": "Foam booster. Can be contaminated with nitrosamines.", "compatible_skin_types": "All"},
    {"name": "Cocamide MEA", "safety_rating": "Safe", "description": "Foam booster and thickener. Generally mild.", "compatible_skin_types": "All"},
    {"name": "Polysorbate 20", "safety_rating": "Safe", "description": "Emulsifier and solvent. Helps ingredients mix.", "compatible_skin_types": "All"},
    {"name": "Polysorbate 80", "safety_rating": "Safe", "description": "Emulsifier. Helps oil and water mix in formulations.", "compatible_skin_types": "All"},
    {"name": "PEG-40 Hydrogenated Castor Oil", "safety_rating": "Moderate", "description": "Emulsifier and solubilizer. Can cause sensitivity in some.", "compatible_skin_types": "All"},
    {"name": "PEG-40 Stearate", "safety_rating": "Moderate", "description": "Emulsifier. May be contaminated with 1,4-dioxane.", "compatible_skin_types": "All"},
    {"name": "TEA-Lauryl Sulfate", "safety_rating": "Irritant", "description": "Surfactant. Can cause irritation and dryness.", "compatible_skin_types": "Oily"},
    {"name": "Ammonium Lauryl Sulfate", "safety_rating": "Irritant", "description": "Foaming surfactant. Can be harsh on skin.", "compatible_skin_types": "Oily"},
    {"name": "Sodium Myreth Sulfate", "safety_rating": "Moderate", "description": "Gentler sulfate. Foaming agent.", "compatible_skin_types": "Oily,All"},
    {"name": "Cocamidopropyl Hydroxysultaine", "safety_rating": "Safe", "description": "Mild surfactant. Gentle cleansing without stripping.", "compatible_skin_types": "All"},
    # Actives - Vitamins
    {"name": "Niacinamide", "safety_rating": "Safe", "description": "Vitamin B3. Minimizes pores, evens tone, strengthens barrier.", "compatible_skin_types": "All"},
    {"name": "Retinol", "safety_rating": "Moderate", "description": "Vitamin A derivative. Promotes cell turnover. Use with sunscreen.", "compatible_skin_types": "Oily,Combination,All"},
    {"name": "Retinol Palmitate", "safety_rating": "Moderate", "description": "Ester form of retinol. Gentler than pure retinol.", "compatible_skin_types": "All"},
    {"name": "Retinal", "safety_rating": "Moderate", "description": "Retinaldehyde. Stronger than retinol, converts faster.", "compatible_skin_types": "Oily,All"},
    {"name": "Adapalene", "safety_rating": "Moderate", "description": "Retinoid. Prescription-strength for acne. Can cause irritation.", "compatible_skin_types": "Oily"},
    {"name": "Tretinoin", "safety_rating": "Moderate", "description": "Prescription retinoid. Strong anti-aging. Use with sunscreen.", "compatible_skin_types": "Oily,Combination"},
    {"name": "Vitamin C", "safety_rating": "Safe", "description": "Ascorbic acid. Antioxidant, brightens skin, boosts collagen.", "compatible_skin_types": "All"},
    {"name": "Ascorbic Acid", "safety_rating": "Safe", "description": "Pure vitamin C. Antioxidant and brightening. Can be irritating at high pH.", "compatible_skin_types": "All"},
    {"name": "L-Ascorbic Acid", "safety_rating": "Safe", "description": "Active form of vitamin C. Most effective but unstable.", "compatible_skin_types": "All"},
    {"name": "Sodium Ascorbyl Phosphate", "safety_rating": "Safe", "description": "Stable vitamin C derivative. Gentle and effective.", "compatible_skin_types": "All"},
    {"name": "Magnesium Ascorbyl Phosphate", "safety_rating": "Safe", "description": "Stable vitamin C. Gentle. Good for sensitive skin.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Ascorbyl Glucoside", "safety_rating": "Safe", "description": "Stable vitamin C derivative. Converts to ascorbic acid on skin.", "compatible_skin_types": "All"},
    {"name": "Ethyl Ascorbic Acid", "safety_rating": "Safe", "description": "Stable vitamin C derivative. Brightening and antioxidant.", "compatible_skin_types": "All"},
    {"name": "Tetrahexyldecyl Ascorbate", "safety_rating": "Safe", "description": "Oil-soluble vitamin C. Stable and penetrates well.", "compatible_skin_types": "All"},
    {"name": "Vitamin E", "safety_rating": "Safe", "description": "Tocopherol. Antioxidant and moisturizer.", "compatible_skin_types": "All"},
    {"name": "Tocopherol", "safety_rating": "Safe", "description": "Vitamin E. Antioxidant. Protects against free radicals.", "compatible_skin_types": "All"},
    {"name": "Tocopheryl Acetate", "safety_rating": "Safe", "description": "Stable form of vitamin E. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Alpha Tocopherol", "safety_rating": "Safe", "description": "Most active form of vitamin E. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Vitamin A", "safety_rating": "Moderate", "description": "Retinal. Supports cell turnover. Use with caution.", "compatible_skin_types": "All"},
    {"name": "Vitamin B5", "safety_rating": "Safe", "description": "Panthenol. Soothing and hydrating. Helps skin barrier.", "compatible_skin_types": "All"},
    {"name": "Panthenol", "safety_rating": "Safe", "description": "Provitamin B5. Hydrating and soothing. Wound healing.", "compatible_skin_types": "All"},
    {"name": "D-Panthenol", "safety_rating": "Safe", "description": "Active form of panthenol. Deeply hydrating.", "compatible_skin_types": "All"},
    {"name": "Biotin", "safety_rating": "Safe", "description": "Vitamin B7. Supports skin health and keratin production.", "compatible_skin_types": "All"},
    {"name": "Folic Acid", "safety_rating": "Safe", "description": "Vitamin B9. Supports cell repair and regeneration.", "compatible_skin_types": "All"},
    {"name": "Pyridoxine HCl", "safety_rating": "Safe", "description": "Vitamin B6. Supports skin metabolism.", "compatible_skin_types": "All"},
    {"name": "Thiamine HCl", "safety_rating": "Safe", "description": "Vitamin B1. Supports skin health.", "compatible_skin_types": "All"},
    {"name": "Riboflavin", "safety_rating": "Safe", "description": "Vitamin B2. Supports cellular energy.", "compatible_skin_types": "All"},
    {"name": "Vitamin K", "safety_rating": "Safe", "description": "Phylloquinone. May help with dark circles and bruising.", "compatible_skin_types": "All"},
    {"name": "Vitamin D", "safety_rating": "Safe", "description": "Supports skin health and immune function.", "compatible_skin_types": "All"},
    # Exfoliants - AHAs
    {"name": "Glycolic Acid", "safety_rating": "Moderate", "description": "AHA. Exfoliates surface. Small molecule penetrates well. Use sunscreen.", "compatible_skin_types": "Oily,Combination,All"},
    {"name": "Mandelic Acid", "safety_rating": "Safe", "description": "Gentle AHA. Larger molecule. Good for sensitive skin.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Malic Acid", "safety_rating": "Moderate", "description": "AHA. Exfoliating. Often used with other AHAs.", "compatible_skin_types": "Oily,All"},
    {"name": "Tartaric Acid", "safety_rating": "Moderate", "description": "AHA. Exfoliating and antioxidant.", "compatible_skin_types": "All"},
    {"name": "Citric Acid", "safety_rating": "Safe", "description": "AHA and pH adjuster. Mild exfoliation.", "compatible_skin_types": "All"},
    {"name": "Gluconolactone", "safety_rating": "Safe", "description": "PHA. Gentle exfoliant. Good for sensitive skin.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Galactose", "safety_rating": "Safe", "description": "PHA. Gentle exfoliation. Hydrating.", "compatible_skin_types": "All"},
    {"name": "Lactobionic Acid", "safety_rating": "Safe", "description": "PHA. Gentle exfoliant. Antioxidant.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Glucose", "safety_rating": "Safe", "description": "PHA. Gentle exfoliation. Hydrating.", "compatible_skin_types": "All"},
    {"name": "BHA / Salicylic Acid", "safety_rating": "Moderate", "description": "Beta hydroxy acid. Oil-soluble. Exfoliates pores. Good for acne.", "compatible_skin_types": "Oily,Combination,All"},
    {"name": "Salicylic Acid", "safety_rating": "Moderate", "description": "BHA. Penetrates pores. Exfoliates and anti-acne.", "compatible_skin_types": "Oily,Combination,All"},
    {"name": "Betaine Salicylate", "safety_rating": "Safe", "description": "Gentler alternative to salicylic acid. BHA-like benefits.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Willow Bark Extract", "safety_rating": "Safe", "description": "Natural source of salicylic acid. Gentle exfoliation.", "compatible_skin_types": "All"},
    {"name": "Azelaic Acid", "safety_rating": "Safe", "description": "Gentle acid. Anti-inflammatory, brightening, anti-acne.", "compatible_skin_types": "All"},
    {"name": "Phytic Acid", "safety_rating": "Safe", "description": "Chelating agent. Mild exfoliation and antioxidant.", "compatible_skin_types": "All"},
    {"name": "Kojic Acid", "safety_rating": "Moderate", "description": "Brightening agent. Inhibits melanin. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Alpha Arbutin", "safety_rating": "Safe", "description": "Brightening. Inhibits melanin production. Gentle.", "compatible_skin_types": "All"},
    {"name": "Arbutin", "safety_rating": "Safe", "description": "Brightening ingredient. Reduces hyperpigmentation.", "compatible_skin_types": "All"},
    {"name": "Tranexamic Acid", "safety_rating": "Safe", "description": "Brightening. Reduces melasma and hyperpigmentation.", "compatible_skin_types": "All"},
    # Antioxidants
    {"name": "Resveratrol", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging. Protects from UV damage.", "compatible_skin_types": "All"},
    {"name": "Ferulic Acid", "safety_rating": "Safe", "description": "Antioxidant. Stabilizes vitamin C. Protects from free radicals.", "compatible_skin_types": "All"},
    {"name": "Green Tea Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-inflammatory. Calming.", "compatible_skin_types": "All"},
    {"name": "Camellia Sinensis Leaf Extract", "safety_rating": "Safe", "description": "INCI for green tea. Antioxidant and soothing.", "compatible_skin_types": "All"},
    {"name": "Caffeine", "safety_rating": "Safe", "description": "Antioxidant. Reduces puffiness. May help dark circles.", "compatible_skin_types": "All"},
    {"name": "Coenzyme Q10", "safety_rating": "Safe", "description": "Ubiquinone. Antioxidant. Anti-aging energy for cells.", "compatible_skin_types": "All"},
    {"name": "Ubiquinone", "safety_rating": "Safe", "description": "CoQ10. Antioxidant. Supports cellular energy.", "compatible_skin_types": "All"},
    {"name": "Superoxide Dismutase", "safety_rating": "Safe", "description": "Enzyme antioxidant. Neutralizes free radicals.", "compatible_skin_types": "All"},
    {"name": "Glutathione", "safety_rating": "Safe", "description": "Powerful antioxidant. Brightening.", "compatible_skin_types": "All"},
    {"name": "Ergothioneine", "safety_rating": "Safe", "description": "Amino acid antioxidant. Protects from oxidative stress.", "compatible_skin_types": "All"},
    {"name": "Astaxanthin", "safety_rating": "Safe", "description": "Carotenoid antioxidant. Powerful anti-aging.", "compatible_skin_types": "All"},
    {"name": "Lycopene", "safety_rating": "Safe", "description": "Carotenoid antioxidant. Protects from UV.", "compatible_skin_types": "All"},
    {"name": "Beta Carotene", "safety_rating": "Safe", "description": "Provitamin A. Antioxidant. Protects skin.", "compatible_skin_types": "All"},
    {"name": "Selenium", "safety_rating": "Safe", "description": "Trace mineral. Antioxidant. Supports skin health.", "compatible_skin_types": "All"},
    {"name": "Zinc Oxide", "safety_rating": "Safe", "description": "Mineral sunscreen and soothing agent. Protects and calms.", "compatible_skin_types": "All"},
    {"name": "Titanium Dioxide", "safety_rating": "Safe", "description": "Mineral sunscreen. Physical UV blocker.", "compatible_skin_types": "All"},
    {"name": "Centella Asiatica", "safety_rating": "Safe", "description": "Cica. Anti-inflammatory. Wound healing. Calming.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Centella Asiatica Extract", "safety_rating": "Safe", "description": "Madecassoside. Wound healing and soothing.", "compatible_skin_types": "All"},
    {"name": "Madecassoside", "safety_rating": "Safe", "description": "Centella compound. Anti-inflammatory and healing.", "compatible_skin_types": "All"},
    {"name": "Asiaticoside", "safety_rating": "Safe", "description": "Centella compound. Wound healing.", "compatible_skin_types": "All"},
    {"name": "Licorice Root Extract", "safety_rating": "Safe", "description": "Glycyrrhiza. Brightening and anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Glycyrrhiza Glabra Root Extract", "safety_rating": "Safe", "description": "Licorice. Anti-inflammatory and brightening.", "compatible_skin_types": "All"},
    {"name": "Chamomile Extract", "safety_rating": "Safe", "description": "Calming and anti-inflammatory. Soothing.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Calendula Extract", "safety_rating": "Safe", "description": "Marigold. Anti-inflammatory and healing.", "compatible_skin_types": "All"},
    {"name": "Oat Extract", "safety_rating": "Safe", "description": "Avena sativa. Soothing and anti-itch. Colloidal oatmeal.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Avena Sativa Kernel Extract", "safety_rating": "Safe", "description": "Oat. Soothing and anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Allantoin", "safety_rating": "Safe", "description": "Soothing and healing. Promotes cell repair.", "compatible_skin_types": "All"},
    {"name": "Bisabolol", "safety_rating": "Safe", "description": "Chamomile-derived. Anti-inflammatory and soothing.", "compatible_skin_types": "All"},
    {"name": "Alpha Bisabolol", "safety_rating": "Safe", "description": "Soothing ingredient. Reduces irritation.", "compatible_skin_types": "All"},
    # Emollients & Oils
    {"name": "Jojoba Oil", "safety_rating": "Safe", "description": "Wax ester. Mimics sebum. Non-comedogenic.", "compatible_skin_types": "All"},
    {"name": "Simmondsia Chinensis Seed Oil", "safety_rating": "Safe", "description": "Jojoba oil INCI. Moisturizing and balancing.", "compatible_skin_types": "All"},
    {"name": "Argan Oil", "safety_rating": "Safe", "description": "Rich in vitamin E. Nourishing and antioxidant.", "compatible_skin_types": "Dry,All"},
    {"name": "Squalane", "safety_rating": "Safe", "description": "Lightweight emollient. Mimics natural sebum.", "compatible_skin_types": "All"},
    {"name": "Squalene", "safety_rating": "Safe", "description": "Precursor to squalane. Natural moisturizer.", "compatible_skin_types": "All"},
    {"name": "Rosehip Oil", "safety_rating": "Safe", "description": "Rich in vitamin A and fatty acids. Regenerating.", "compatible_skin_types": "All"},
    {"name": "Marula Oil", "safety_rating": "Safe", "description": "Lightweight oil. Antioxidant and moisturizing.", "compatible_skin_types": "All"},
    {"name": "Grapeseed Oil", "safety_rating": "Safe", "description": "Light oil. Antioxidant. Non-comedogenic.", "compatible_skin_types": "Oily,All"},
    {"name": "Sunflower Seed Oil", "safety_rating": "Safe", "description": "Light emollient. Rich in vitamin E.", "compatible_skin_types": "All"},
    {"name": "Coconut Oil", "safety_rating": "Moderate", "description": "Emollient. Can be comedogenic for some. Use with caution on face.", "compatible_skin_types": "Dry,All"},
    {"name": "Caprylic/Capric Triglyceride", "safety_rating": "Safe", "description": "Fractionated coconut oil. Light emollient. Non-comedogenic.", "compatible_skin_types": "All"},
    {"name": "Shea Butter", "safety_rating": "Safe", "description": "Rich emollient. Nourishing and anti-inflammatory.", "compatible_skin_types": "Dry,All"},
    {"name": "Butyrospermum Parkii Butter", "safety_rating": "Safe", "description": "Shea butter INCI. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Cocoa Butter", "safety_rating": "Safe", "description": "Rich emollient. Can be comedogenic for some.", "compatible_skin_types": "Dry,All"},
    {"name": "Mango Butter", "safety_rating": "Safe", "description": "Light butter. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Avocado Oil", "safety_rating": "Safe", "description": "Rich in fatty acids. Nourishing.", "compatible_skin_types": "Dry,All"},
    {"name": "Olive Oil", "safety_rating": "Safe", "description": "Emollient. Antioxidant. Can be heavy for oily skin.", "compatible_skin_types": "Dry,All"},
    {"name": "Sweet Almond Oil", "safety_rating": "Safe", "description": "Light emollient. Rich in vitamin E.", "compatible_skin_types": "All"},
    {"name": "Tea Tree Oil", "safety_rating": "Moderate", "description": "Antimicrobial. Good for acne. Can be irritating if undiluted.", "compatible_skin_types": "Oily,All"},
    {"name": "Melaleuca Alternifolia Leaf Oil", "safety_rating": "Moderate", "description": "Tea tree oil INCI. Antimicrobial.", "compatible_skin_types": "Oily"},
    {"name": "Lavender Oil", "safety_rating": "Moderate", "description": "Calming. Can cause sensitivity in some.", "compatible_skin_types": "All"},
    {"name": "Lavandula Angustifolia Oil", "safety_rating": "Moderate", "description": "Lavender INCI. Soothing.", "compatible_skin_types": "All"},
    {"name": "Chamomile Oil", "safety_rating": "Safe", "description": "Calming and anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Rose Oil", "safety_rating": "Safe", "description": "Antioxidant. Fragrance. Can be expensive.", "compatible_skin_types": "All"},
    {"name": "Neroli Oil", "safety_rating": "Safe", "description": "Citrus-derived. Calming. Can cause photosensitivity.", "compatible_skin_types": "All"},
    {"name": "Eucalyptus Oil", "safety_rating": "Irritant", "description": "Can be irritating. Use with caution.", "compatible_skin_types": "All"},
    {"name": "Peppermint Oil", "safety_rating": "Irritant", "description": "Cooling. Can cause irritation. Avoid on sensitive skin.", "compatible_skin_types": "Oily"},
    {"name": "Cetearyl Alcohol", "safety_rating": "Safe", "description": "Fatty alcohol. Emollient and emulsifier. Not drying.", "compatible_skin_types": "All"},
    {"name": "Cetyl Alcohol", "safety_rating": "Safe", "description": "Fatty alcohol. Emollient. Helps thicken.", "compatible_skin_types": "All"},
    {"name": "Stearyl Alcohol", "safety_rating": "Safe", "description": "Fatty alcohol. Emollient.", "compatible_skin_types": "All"},
    {"name": "Isopropyl Myristate", "safety_rating": "Moderate", "description": "Emollient. Can be comedogenic for some.", "compatible_skin_types": "All"},
    {"name": "Isopropyl Palmitate", "safety_rating": "Moderate", "description": "Emollient. Can be comedogenic.", "compatible_skin_types": "All"},
    {"name": "Dimethicone", "safety_rating": "Safe", "description": "Silicone. Creates smooth barrier. Non-comedogenic.", "compatible_skin_types": "All"},
    {"name": "Cyclopentasiloxane", "safety_rating": "Moderate", "description": "Volatile silicone. Evaporates. Can be drying long-term.", "compatible_skin_types": "All"},
    {"name": "Cyclohexasiloxane", "safety_rating": "Moderate", "description": "Volatile silicone. Lightweight.", "compatible_skin_types": "All"},
    {"name": "Phenyl Trimethicone", "safety_rating": "Safe", "description": "Silicone. Adds slip and shine.", "compatible_skin_types": "All"},
    {"name": "Amodimethicone", "safety_rating": "Safe", "description": "Silicone. Conditions hair and skin.", "compatible_skin_types": "All"},
    {"name": "Ceramide NP", "safety_rating": "Safe", "description": "Barrier lipid. Restores skin barrier.", "compatible_skin_types": "All"},
    {"name": "Ceramide AP", "safety_rating": "Safe", "description": "Barrier lipid. Strengthens skin barrier.", "compatible_skin_types": "All"},
    {"name": "Ceramide EOP", "safety_rating": "Safe", "description": "Barrier lipid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Cholesterol", "safety_rating": "Safe", "description": "Barrier lipid. Restores skin barrier.", "compatible_skin_types": "All"},
    {"name": "Phytosphingosine", "safety_rating": "Safe", "description": "Barrier lipid. Antimicrobial.", "compatible_skin_types": "All"},
    {"name": "Sphingolipids", "safety_rating": "Safe", "description": "Barrier lipids. Support skin barrier function.", "compatible_skin_types": "All"},
    {"name": "Linoleic Acid", "safety_rating": "Safe", "description": "Omega-6 fatty acid. Supports barrier.", "compatible_skin_types": "All"},
    {"name": "Linolenic Acid", "safety_rating": "Safe", "description": "Omega-3 fatty acid. Anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Oleic Acid", "safety_rating": "Safe", "description": "Omega-9. Emollient. Can be comedogenic for some.", "compatible_skin_types": "Dry,All"},
    {"name": "Palmitic Acid", "safety_rating": "Safe", "description": "Saturated fatty acid. Emollient.", "compatible_skin_types": "All"},
    {"name": "Stearic Acid", "safety_rating": "Safe", "description": "Fatty acid. Emulsifier and emollient.", "compatible_skin_types": "All"},
    # Peptides
    {"name": "Palmitoyl Pentapeptide-4", "safety_rating": "Safe", "description": "Matrixyl. Peptide. Supports collagen.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Tetrapeptide-7", "safety_rating": "Safe", "description": "Peptide. Anti-inflammatory. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Tripeptide-1", "safety_rating": "Safe", "description": "Peptide. Collagen support.", "compatible_skin_types": "All"},
    {"name": "Copper Peptide", "safety_rating": "Safe", "description": "GHK-Cu. Wound healing. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Tripeptide-38", "safety_rating": "Safe", "description": "Peptide. Matrixyl 3000. Collagen support.", "compatible_skin_types": "All"},
    {"name": "Acetyl Hexapeptide-8", "safety_rating": "Safe", "description": "Argireline. Relaxes expression lines.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Tetrapeptide-36", "safety_rating": "Safe", "description": "Peptide. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Hexapeptide-12", "safety_rating": "Safe", "description": "Peptide. Collagen support.", "compatible_skin_types": "All"},
    {"name": "Acetyl Tetrapeptide-5", "safety_rating": "Safe", "description": "Peptide. Reduces dark circles.", "compatible_skin_types": "All"},
    {"name": "Palmitoyl Dipeptide-5", "safety_rating": "Safe", "description": "Peptide. Collagen support.", "compatible_skin_types": "All"},
    {"name": "Carnosine", "safety_rating": "Safe", "description": "Dipeptide. Antioxidant. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Glutathione", "safety_rating": "Safe", "description": "Tripeptide. Antioxidant. Brightening.", "compatible_skin_types": "All"},
    {"name": "Collagen", "safety_rating": "Safe", "description": "Protein. Moisturizing. Topical collagen doesn't penetrate.", "compatible_skin_types": "All"},
    {"name": "Hydrolyzed Collagen", "safety_rating": "Safe", "description": "Smaller collagen. Film-forming. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Elastin", "safety_rating": "Safe", "description": "Protein. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Keratin", "safety_rating": "Safe", "description": "Protein. Strengthening.", "compatible_skin_types": "All"},
    {"name": "Silk Amino Acids", "safety_rating": "Safe", "description": "Film-forming. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Sodium Hyaluronate Crosspolymer", "safety_rating": "Safe", "description": "Cross-linked HA. Longer-lasting hydration.", "compatible_skin_types": "All"},
    {"name": "Hydrolyzed Hyaluronic Acid", "safety_rating": "Safe", "description": "Low molecular weight HA. Deeper penetration.", "compatible_skin_types": "All"},
    # Sunscreen agents
    {"name": "Avobenzone", "safety_rating": "Moderate", "description": "Chemical sunscreen. UVA protection. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Octinoxate", "safety_rating": "Moderate", "description": "Octyl methoxycinnamate. UVB filter. Hormone concerns.", "compatible_skin_types": "All"},
    {"name": "Octinoxate", "safety_rating": "Moderate", "description": "Chemical UVB filter. Can cause hormonal disruption.", "compatible_skin_types": "All"},
    {"name": "Octocrylene", "safety_rating": "Moderate", "description": "Chemical sunscreen. UVB. Can cause allergic reactions.", "compatible_skin_types": "All"},
    {"name": "Homosalate", "safety_rating": "Moderate", "description": "Chemical UVB filter. Hormone disruptor concern.", "compatible_skin_types": "All"},
    {"name": "Oxybenzone", "safety_rating": "Avoid", "description": "Chemical sunscreen. Hormone disruptor. Banned in some places.", "compatible_skin_types": "All"},
    {"name": "Octisalate", "safety_rating": "Moderate", "description": "Chemical UVB filter. Generally safe.", "compatible_skin_types": "All"},
    {"name": "Methylisothiazolinone", "safety_rating": "Irritant", "description": "Preservative. Strong allergen. Avoid in leave-on.", "compatible_skin_types": "All"},
    {"name": "Benzophenone-3", "safety_rating": "Avoid", "description": "Oxybenzone. Hormone disruptor.", "compatible_skin_types": "All"},
    {"name": "Benzophenone-4", "safety_rating": "Moderate", "description": "Sulisobenzone. UV filter. Less concerning than BP-3.", "compatible_skin_types": "All"},
    {"name": "Tinosorb S", "safety_rating": "Safe", "description": "Broad-spectrum filter. Not in US FDA.", "compatible_skin_types": "All"},
    {"name": "Tinosorb M", "safety_rating": "Safe", "description": "Broad-spectrum filter. EU approved.", "compatible_skin_types": "All"},
    {"name": "Uvinul A Plus", "safety_rating": "Safe", "description": "UVA filter. EU approved.", "compatible_skin_types": "All"},
    {"name": "Uvinul T 150", "safety_rating": "Safe", "description": "UVB filter. EU approved.", "compatible_skin_types": "All"},
    {"name": "Mexoryl SX", "safety_rating": "Safe", "description": "UVA filter. L'Oréal patent.", "compatible_skin_types": "All"},
    {"name": "Mexoryl XL", "safety_rating": "Safe", "description": "Broad-spectrum. L'Oréal patent.", "compatible_skin_types": "All"},
    {"name": "Ensulizole", "safety_rating": "Safe", "description": "Phenylbenzimidazole. UVB filter.", "compatible_skin_types": "All"},
    {"name": "Methyl Anthranilate", "safety_rating": "Moderate", "description": "UVB filter. Can cause sensitivity.", "compatible_skin_types": "All"},
    # Thickeners & Emulsifiers
    {"name": "Carbomer", "safety_rating": "Safe", "description": "Synthetic thickener. Creates gel texture.", "compatible_skin_types": "All"},
    {"name": "Xanthan Gum", "safety_rating": "Safe", "description": "Natural thickener. Creates gel.", "compatible_skin_types": "All"},
    {"name": "Hydroxyethylcellulose", "safety_rating": "Safe", "description": "Cellulose thickener. Gentle.", "compatible_skin_types": "All"},
    {"name": "Hydroxypropyl Methylcellulose", "safety_rating": "Safe", "description": "Cellulose thickener.", "compatible_skin_types": "All"},
    {"name": "Acrylates", "safety_rating": "Moderate", "description": "Synthetic polymer. Thickener. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", "safety_rating": "Safe", "description": "Thickener. Creates gel.", "compatible_skin_types": "All"},
    {"name": "Cetearyl Alcohol", "safety_rating": "Safe", "description": "Emulsifier and emollient.", "compatible_skin_types": "All"},
    {"name": "Ceteareth-20", "safety_rating": "Safe", "description": "Emulsifier. Helps oil and water mix.", "compatible_skin_types": "All"},
    {"name": "Stearyl Alcohol", "safety_rating": "Safe", "description": "Emollient and thickener.", "compatible_skin_types": "All"},
    {"name": "Behenyl Alcohol", "safety_rating": "Safe", "description": "Fatty alcohol. Emollient.", "compatible_skin_types": "All"},
    {"name": "Glyceryl Stearate", "safety_rating": "Safe", "description": "Emulsifier. Helps oil and water mix.", "compatible_skin_types": "All"},
    {"name": "PEG-100 Stearate", "safety_rating": "Moderate", "description": "Emulsifier. May contain 1,4-dioxane.", "compatible_skin_types": "All"},
    {"name": "Lecithin", "safety_rating": "Safe", "description": "Natural emulsifier. From soy or egg.", "compatible_skin_types": "All"},
    {"name": "Soy Lecithin", "safety_rating": "Safe", "description": "Natural emulsifier. From soybeans.", "compatible_skin_types": "All"},
    {"name": "Cetearyl Glucoside", "safety_rating": "Safe", "description": "Plant-derived emulsifier. Gentle.", "compatible_skin_types": "All"},
    {"name": "Sodium Stearoyl Lactylate", "safety_rating": "Safe", "description": "Emulsifier. Helps oil and water mix.", "compatible_skin_types": "All"},
    {"name": "Potassium Cetyl Phosphate", "safety_rating": "Safe", "description": "Emulsifier. Creates stable emulsions.", "compatible_skin_types": "All"},
    {"name": "Sodium Lactate", "safety_rating": "Safe", "description": "Humectant and pH adjuster.", "compatible_skin_types": "All"},
    {"name": "Sodium Citrate", "safety_rating": "Safe", "description": "pH adjuster and chelator.", "compatible_skin_types": "All"},
    {"name": "Triethanolamine", "safety_rating": "Moderate", "description": "pH adjuster. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Sodium Hydroxide", "safety_rating": "Moderate", "description": "Lye. pH adjuster. Used in small amounts.", "compatible_skin_types": "All"},
    {"name": "Potassium Hydroxide", "safety_rating": "Moderate", "description": "pH adjuster. Used in small amounts.", "compatible_skin_types": "All"},
    {"name": "Lactic Acid", "safety_rating": "Moderate", "description": "AHA and pH adjuster.", "compatible_skin_types": "All"},
    {"name": "Sodium Benzoate", "safety_rating": "Safe", "description": "Preservative.", "compatible_skin_types": "All"},
    {"name": "Potassium Sorbate", "safety_rating": "Safe", "description": "Preservative.", "compatible_skin_types": "All"},
    # More botanical extracts
    {"name": "Witch Hazel", "safety_rating": "Moderate", "description": "Astringent. Can be drying. Alcohol-free versions gentler.", "compatible_skin_types": "Oily,All"},
    {"name": "Hamamelis Virginiana Extract", "safety_rating": "Moderate", "description": "Witch hazel INCI. Astringent.", "compatible_skin_types": "Oily"},
    {"name": "Bakuchiol", "safety_rating": "Safe", "description": "Plant retinol alternative. Gentle anti-aging.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Bakuchiol", "safety_rating": "Safe", "description": "Retinol alternative. Gentle. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Resveratrol", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Curcumin", "safety_rating": "Safe", "description": "Turmeric antioxidant. Anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Turmeric Extract", "safety_rating": "Safe", "description": "Curcuma longa. Anti-inflammatory. Can stain.", "compatible_skin_types": "All"},
    {"name": "Ginger Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Ginseng Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging. Energizing.", "compatible_skin_types": "All"},
    {"name": "Ginkgo Biloba Extract", "safety_rating": "Safe", "description": "Antioxidant. Improves circulation.", "compatible_skin_types": "All"},
    {"name": "White Tea Extract", "safety_rating": "Safe", "description": "Antioxidant. Gentle.", "compatible_skin_types": "All"},
    {"name": "Black Tea Extract", "safety_rating": "Safe", "description": "Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Rooibos Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Pomegranate Extract", "safety_rating": "Safe", "description": "Antioxidant. Ellagic acid.", "compatible_skin_types": "All"},
    {"name": "Blueberry Extract", "safety_rating": "Safe", "description": "Antioxidant. Anthocyanins.", "compatible_skin_types": "All"},
    {"name": "Acai Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Goji Berry Extract", "safety_rating": "Safe", "description": "Antioxidant. Vitamin C.", "compatible_skin_types": "All"},
    {"name": "Seaweed Extract", "safety_rating": "Safe", "description": "Minerals. Hydrating.", "compatible_skin_types": "All"},
    {"name": "Spirulina Extract", "safety_rating": "Safe", "description": "Antioxidant. Anti-inflammatory.", "compatible_skin_types": "All"},
    {"name": "Chlorella Extract", "safety_rating": "Safe", "description": "Antioxidant. Detoxifying.", "compatible_skin_types": "All"},
    {"name": "Mushroom Extract", "safety_rating": "Safe", "description": "Reishi, tremella. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Tremella Mushroom", "safety_rating": "Safe", "description": "Snow mushroom. Hydrating. Holds moisture.", "compatible_skin_types": "All"},
    {"name": "Reishi Mushroom", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "Snow Mushroom", "safety_rating": "Safe", "description": "Tremella. Hydrating humectant.", "compatible_skin_types": "All"},
    {"name": "Rice Extract", "safety_rating": "Safe", "description": "Brightening. Soothing.", "compatible_skin_types": "All"},
    {"name": "Oryza Sativa Extract", "safety_rating": "Safe", "description": "Rice. Brightening.", "compatible_skin_types": "All"},
    {"name": "Sake", "safety_rating": "Safe", "description": "Rice ferment. Brightening.", "compatible_skin_types": "All"},
    {"name": "Galactomyces Ferment Filtrate", "safety_rating": "Safe", "description": "Sake ferment. Brightening. Pitera-like.", "compatible_skin_types": "All"},
    {"name": "Bifida Ferment Lysate", "safety_rating": "Safe", "description": "Probiotic. Strengthens barrier.", "compatible_skin_types": "All"},
    {"name": "Lactobacillus Ferment", "safety_rating": "Safe", "description": "Probiotic. Calming.", "compatible_skin_types": "All"},
    {"name": "Saccharomyces Ferment", "safety_rating": "Safe", "description": "Yeast ferment. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Niacin", "safety_rating": "Safe", "description": "Niacinamide precursor. Vitamin B3.", "compatible_skin_types": "All"},
    {"name": "Tocotrienols", "safety_rating": "Safe", "description": "Vitamin E variant. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Alpha Lipoic Acid", "safety_rating": "Safe", "description": "Antioxidant. Anti-aging.", "compatible_skin_types": "All"},
    {"name": "N-Acetyl Glucosamine", "safety_rating": "Safe", "description": "Amino sugar. Supports barrier. Brightening.", "compatible_skin_types": "All"},
    {"name": "Adenosine", "safety_rating": "Safe", "description": "Nucleotide. Anti-aging. Reduces wrinkles.", "compatible_skin_types": "All"},
    {"name": "Saccharomyces Ferment Filtrate", "safety_rating": "Safe", "description": "Yeast ferment. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Phenoxyethanol", "safety_rating": "Moderate", "description": "Preservative. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Ethylhexylglycerin", "safety_rating": "Safe", "description": "Preservative booster.", "compatible_skin_types": "All"},
    {"name": "Sodium Lauroyl Lactylate", "safety_rating": "Safe", "description": "Emulsifier. Gentle.", "compatible_skin_types": "All"},
    {"name": "Sodium Behenoyl Lactylate", "safety_rating": "Safe", "description": "Emulsifier.", "compatible_skin_types": "All"},
    {"name": "Sodium Isostearoyl Lactylate", "safety_rating": "Safe", "description": "Emulsifier.", "compatible_skin_types": "All"},
    {"name": "Sodium Palmitoyl Proline", "safety_rating": "Safe", "description": "Amino acid derivative. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Sodium PCA", "safety_rating": "Safe", "description": "Natural moisturizing factor.", "compatible_skin_types": "All"},
    {"name": "PCA", "safety_rating": "Safe", "description": "Pyrrolidone carboxylic acid. NMF.", "compatible_skin_types": "All"},
    {"name": "Sodium Lactate", "safety_rating": "Safe", "description": "Humectant. NMF.", "compatible_skin_types": "All"},
    {"name": "Sodium Lactate", "safety_rating": "Safe", "description": "Natural moisturizing factor. Humectant.", "compatible_skin_types": "All"},
    {"name": "Amino Acids", "safety_rating": "Safe", "description": "Building blocks. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Glycine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Proline", "safety_rating": "Safe", "description": "Amino acid. Collagen support.", "compatible_skin_types": "All"},
    {"name": "Serine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Threonine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Alanine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Lysine", "safety_rating": "Safe", "description": "Amino acid. Supports barrier.", "compatible_skin_types": "All"},
    {"name": "Arginine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Histidine", "safety_rating": "Safe", "description": "Amino acid. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Cysteine", "safety_rating": "Safe", "description": "Amino acid. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Methionine", "safety_rating": "Safe", "description": "Amino acid. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Tryptophan", "safety_rating": "Safe", "description": "Amino acid. Precursor to serotonin.", "compatible_skin_types": "All"},
    {"name": "Phenylalanine", "safety_rating": "Safe", "description": "Amino acid.", "compatible_skin_types": "All"},
    {"name": "Tyrosine", "safety_rating": "Safe", "description": "Amino acid. Melanin precursor.", "compatible_skin_types": "All"},
    {"name": "Valine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Leucine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Isoleucine", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Aspartic Acid", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Glutamic Acid", "safety_rating": "Safe", "description": "Amino acid. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Asparagine", "safety_rating": "Safe", "description": "Amino acid.", "compatible_skin_types": "All"},
    {"name": "Glutamine", "safety_rating": "Safe", "description": "Amino acid. Barrier support.", "compatible_skin_types": "All"},
    {"name": "Copper Gluconate", "safety_rating": "Safe", "description": "Copper peptide. Wound healing.", "compatible_skin_types": "All"},
    {"name": "Zinc Gluconate", "safety_rating": "Safe", "description": "Zinc. Anti-acne. Anti-inflammatory.", "compatible_skin_types": "Oily,All"},
    {"name": "Zinc PCA", "safety_rating": "Safe", "description": "Zinc. Oil control. Anti-acne.", "compatible_skin_types": "Oily,All"},
    {"name": "Magnesium Ascorbyl Phosphate", "safety_rating": "Safe", "description": "Stable vitamin C. Gentle.", "compatible_skin_types": "All"},
    {"name": "Sodium Ascorbate", "safety_rating": "Safe", "description": "Buffered vitamin C. Less irritating.", "compatible_skin_types": "All"},
    {"name": "Calcium Ascorbate", "safety_rating": "Safe", "description": "Buffered vitamin C. Gentle.", "compatible_skin_types": "All"},
    {"name": "Sodium Metabisulfite", "safety_rating": "Moderate", "description": "Antioxidant. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Sodium Sulfite", "safety_rating": "Moderate", "description": "Antioxidant. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "BHT", "safety_rating": "Moderate", "description": "Butylated hydroxytoluene. Antioxidant. Controversial.", "compatible_skin_types": "All"},
    {"name": "BHA", "safety_rating": "Moderate", "description": "Butylated hydroxyanisole. Antioxidant. Controversial.", "compatible_skin_types": "All"},
    {"name": "EDTA", "safety_rating": "Safe", "description": "Chelating agent. Stabilizes formulations.", "compatible_skin_types": "All"},
    {"name": "Disodium EDTA", "safety_rating": "Safe", "description": "Chelating agent. Prevents rancidity.", "compatible_skin_types": "All"},
    {"name": "Tetrasodium EDTA", "safety_rating": "Safe", "description": "Chelating agent.", "compatible_skin_types": "All"},
    {"name": "Sodium Phytate", "safety_rating": "Safe", "description": "Chelating agent. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Phytic Acid", "safety_rating": "Safe", "description": "Chelating agent. Mild exfoliation.", "compatible_skin_types": "All"},
    {"name": "Gluconolactone", "safety_rating": "Safe", "description": "PHA. Gentle exfoliant.", "compatible_skin_types": "Sensitive,All"},
    {"name": "Galactose", "safety_rating": "Safe", "description": "PHA. Gentle exfoliation.", "compatible_skin_types": "All"},
    {"name": "Lactobionic Acid", "safety_rating": "Safe", "description": "PHA. Gentle exfoliant.", "compatible_skin_types": "All"},
    {"name": "Glucuronolactone", "safety_rating": "Safe", "description": "PHA. Gentle exfoliation.", "compatible_skin_types": "All"},
    {"name": "Ribose", "safety_rating": "Safe", "description": "Sugar. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Xylose", "safety_rating": "Safe", "description": "Sugar. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Methyl Gluceth-20", "safety_rating": "Safe", "description": "Humectant. Gentle.", "compatible_skin_types": "All"},
    {"name": "Hydroxypropyl Starch Phosphate", "safety_rating": "Safe", "description": "Oil absorber. Mattifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Silica", "safety_rating": "Safe", "description": "Oil absorber. Mattifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Nylon-12", "safety_rating": "Safe", "description": "Oil absorber. Mattifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Polymethylsilsesquioxane", "safety_rating": "Safe", "description": "Silicone. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Mica", "safety_rating": "Safe", "description": "Mineral. Adds shimmer.", "compatible_skin_types": "All"},
    {"name": "Iron Oxides", "safety_rating": "Safe", "description": "Mineral pigment. Color.", "compatible_skin_types": "All"},
    {"name": "Titanium Dioxide", "safety_rating": "Safe", "description": "Mineral. Sunscreen and pigment.", "compatible_skin_types": "All"},
    {"name": "Bismuth Oxychloride", "safety_rating": "Moderate", "description": "Pearlescent. Can cause sensitivity.", "compatible_skin_types": "All"},
    {"name": "Talc", "safety_rating": "Moderate", "description": "Absorbent. Controversial for inhalation.", "compatible_skin_types": "All"},
    {"name": "Boron Nitride", "safety_rating": "Safe", "description": "Smooth. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Calcium Carbonate", "safety_rating": "Safe", "description": "Absorbent. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Magnesium Stearate", "safety_rating": "Safe", "description": "Lubricant. Improves texture.", "compatible_skin_types": "All"},
    {"name": "Zinc Stearate", "safety_rating": "Safe", "description": "Emollient. Water-repellent.", "compatible_skin_types": "All"},
    {"name": "Aluminum Starch Octenylsuccinate", "safety_rating": "Safe", "description": "Oil absorber. Mattifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Corn Starch", "safety_rating": "Safe", "description": "Absorbent. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Rice Starch", "safety_rating": "Safe", "description": "Absorbent. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Tapioca Starch", "safety_rating": "Safe", "description": "Absorbent. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Potato Starch", "safety_rating": "Safe", "description": "Absorbent. Mattifying.", "compatible_skin_types": "All"},
    {"name": "Wheat Starch", "safety_rating": "Safe", "description": "Absorbent. May contain gluten.", "compatible_skin_types": "All"},
    {"name": "Kaolin", "safety_rating": "Safe", "description": "Clay. Absorbent. Purifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Bentonite", "safety_rating": "Safe", "description": "Clay. Absorbent. Detoxifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Fuller's Earth", "safety_rating": "Safe", "description": "Clay. Absorbent. Oil control.", "compatible_skin_types": "Oily,All"},
    {"name": "French Green Clay", "safety_rating": "Safe", "description": "Clay. Mineral-rich. Purifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Rhassoul Clay", "safety_rating": "Safe", "description": "Moroccan clay. Detoxifying.", "compatible_skin_types": "All"},
    {"name": "Charcoal", "safety_rating": "Safe", "description": "Activated charcoal. Absorbent. Purifying.", "compatible_skin_types": "Oily,All"},
    {"name": "Activated Charcoal", "safety_rating": "Safe", "description": "Absorbent. Draws out impurities.", "compatible_skin_types": "Oily,All"},
    {"name": "Cocoa Butter", "safety_rating": "Safe", "description": "Rich emollient. Can be comedogenic.", "compatible_skin_types": "Dry,All"},
    {"name": "Theobroma Cacao Butter", "safety_rating": "Safe", "description": "Cocoa butter INCI.", "compatible_skin_types": "All"},
    {"name": "Methylparaben", "safety_rating": "Avoid", "description": "Paraben preservative. Endocrine disruptor.", "compatible_skin_types": "All"},
    {"name": "Propylparaben", "safety_rating": "Avoid", "description": "Paraben preservative.", "compatible_skin_types": "All"},
    {"name": "Benzyl Alcohol", "safety_rating": "Moderate", "description": "Preservative. Can cause irritation.", "compatible_skin_types": "All"},
    {"name": "Propylene Glycol", "safety_rating": "Safe", "description": "Humectant and solvent.", "compatible_skin_types": "All"},
    {"name": "Dipropylene Glycol", "safety_rating": "Safe", "description": "Humectant. Solvent.", "compatible_skin_types": "All"},
    {"name": "Hexylene Glycol", "safety_rating": "Safe", "description": "Humectant. Solvent.", "compatible_skin_types": "All"},
    {"name": "1,2-Hexanediol", "safety_rating": "Safe", "description": "Humectant. Preservative booster.", "compatible_skin_types": "All"},
    {"name": "Sodium Chloride", "safety_rating": "Safe", "description": "Salt. Thickener. Can be drying.", "compatible_skin_types": "All"},
    {"name": "Potassium Chloride", "safety_rating": "Safe", "description": "Electrolyte. Thickener.", "compatible_skin_types": "All"},
    {"name": "Magnesium Chloride", "safety_rating": "Safe", "description": "Mineral. Supports skin.", "compatible_skin_types": "All"},
    {"name": "Calcium Chloride", "safety_rating": "Safe", "description": "Mineral. Thickener.", "compatible_skin_types": "All"},
    {"name": "Sodium Gluconate", "safety_rating": "Safe", "description": "Chelating agent. Gentle.", "compatible_skin_types": "All"},
    {"name": "Gluconic Acid", "safety_rating": "Safe", "description": "Chelating agent.", "compatible_skin_types": "All"},
    {"name": "Sodium Phytate", "safety_rating": "Safe", "description": "Chelating agent. Antioxidant.", "compatible_skin_types": "All"},
    {"name": "Inositol", "safety_rating": "Safe", "description": "Sugar alcohol. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Mannitol", "safety_rating": "Safe", "description": "Sugar alcohol. Humectant.", "compatible_skin_types": "All"},
    {"name": "Maltitol", "safety_rating": "Safe", "description": "Sugar alcohol. Humectant.", "compatible_skin_types": "All"},
    {"name": "Hydrogenated Starch Hydrolysate", "safety_rating": "Safe", "description": "Humectant. Moisturizing.", "compatible_skin_types": "All"},
    {"name": "Sodium Hyaluronate", "safety_rating": "Safe", "description": "Sodium salt of hyaluronic acid. Humectant.", "compatible_skin_types": "All"},
    {"name": "Hydrolyzed Sodium Hyaluronate", "safety_rating": "Safe", "description": "Low molecular weight HA. Deeper penetration.", "compatible_skin_types": "All"},
    {"name": "Hyaluronic Acid", "safety_rating": "Safe", "description": "Powerful humectant. Holds moisture.", "compatible_skin_types": "All"},
    {"name": "Polyglutamic Acid", "safety_rating": "Safe", "description": "Humectant. Holds 4x more moisture than HA.", "compatible_skin_types": "All"},
    {"name": "Sodium Polyglutamate", "safety_rating": "Safe", "description": "Polyglutamic acid salt. Humectant.", "compatible_skin_types": "All"},
    {"name": "Pullulan", "safety_rating": "Safe", "description": "Polysaccharide. Film-forming.", "compatible_skin_types": "All"},
    {"name": "Hyaluronic Acid", "safety_rating": "Safe", "description": "Humectant. Holds 1000x weight in water.", "compatible_skin_types": "All"},
]
